name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: clean
      run: make clean
    - name: make 
      run: make 
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        path: st
